### ISSUE TITLE
AWS'less deployment

### ISSUE THREAD

**Issue by kvaps** [wireapp/wire-server-deploy#186]
Hi, I'm trying to to deploy wire-server for production environment, I've finished [deploying databases using Ansible](https://docs.wire.com/how-to/install/ansible-VMs.html), I've created [external endpoints](https://docs.okd.io/latest/dev_guide/integrating_external_services.html#defining-a-service-for-an-external-database) for external databases in Kubernetes and deployed wire-server using helm chart with [production values](https://github.com/wireapp/wire-server-deploy/blob/develop/values/wire-server/prod-values.example.yaml).

Everything seems working fine except few external dependencies not described on production deployment guide:

- **brig** depends on [sqs](https://github.com/wireapp/wire-server/blob/226ccb6fa67337961b44b2f4b8c572ce59e9431d/services/brig/brig.integration.yaml#L32) and [dynamodb](https://github.com/wireapp/wire-server/blob/226ccb6fa67337961b44b2f4b8c572ce59e9431d/services/brig/brig.integration.yaml#L33), from the source code I also found out that it also supports [stomp](https://github.com/wireapp/wire-server/blob/226ccb6fa67337961b44b2f4b8c572ce59e9431d/services/brig/brig.integration.yaml#L46), but official helm-chart [hardcoded on sqs](https://github.com/wireapp/wire-server-deploy/blob/fde64ae5fc04b2cf07a39b3d6eea446ddd45eace/charts/brig/templates/configmap.yaml#L53)
- **gundesk** depends on [sqs](https://github.com/wireapp/wire-server/blob/226ccb6fa67337961b44b2f4b8c572ce59e9431d/services/gundeck/gundeck.integration.yaml#L20) and [sns](https://github.com/wireapp/wire-server/blob/226ccb6fa67337961b44b2f4b8c572ce59e9431d/services/gundeck/gundeck.integration.yaml#L21).

Official guide describes fake-aws installation, but if I understood it correct they are not acceptable for production use.

My questions: 
* Is it possible to deploy these services on-premise without using AWS?
* How are they critical, what if I will use fake-aws on production?
* Is there any other alternatives?

Thank you!

**Comment by kvaps** [comment]
Complementing the original issue I can say that I found some opensource tools which implements these interfaces:

* [ActiveMQ](https://activemq.apache.org/) or [RabbitMQ with STOMP Plugin](https://www.rabbitmq.com/stomp.html) implements STOMP
* [Scylla Alternator](https://www.scylladb.com/alternator/) can be used instead DynamoDB. Scylla can also replace Apache Cassandra, I heard it is more fast and less resource consuming.
* [Atlassian LocalStack](https://github.com/localstack/localstack) can statisfy all of these dependencies, it also can have persistent storage.

Is there any suggestions of trying that?

**Comment by jschaul** [comment]
> Everything seems working fine 

I'm glad you were able to install. Were there any parts in the code,scripts or documentation that were unclear or initially confusing for you? Where can we improve documentation? (in case there's something small, feel free to also make a PR)

> except few external dependencies not described on production deployment guide:
> 
>     * **brig** depends on [sqs](https://github.com/wireapp/wire-server/blob/226ccb6fa67337961b44b2f4b8c572ce59e9431d/services/brig/brig.integration.yaml#L32) and [dynamodb](https://github.com/wireapp/wire-server/blob/226ccb6fa67337961b44b2f4b8c572ce59e9431d/services/brig/brig.integration.yaml#L33), from the source code I also found out that it also supports [stomp](https://github.com/wireapp/wire-server/blob/226ccb6fa67337961b44b2f4b8c572ce59e9431d/services/brig/brig.integration.yaml#L46), but official helm-chart [hardcoded on sqs](https://github.com/wireapp/wire-server-deploy/blob/fde64ae5fc04b2cf07a39b3d6eea446ddd45eace/charts/brig/templates/configmap.yaml#L53)
> 
>     * **gundesk** depends on [sqs](https://github.com/wireapp/wire-server/blob/226ccb6fa67337961b44b2f4b8c572ce59e9431d/services/gundeck/gundeck.integration.yaml#L20) and [sns](https://github.com/wireapp/wire-server/blob/226ccb6fa67337961b44b2f4b8c572ce59e9431d/services/gundeck/gundeck.integration.yaml#L21).
> 
> 
> Official guide describes fake-aws installation, but if I understood it correct they are not acceptable for production use.

At the moment, you have two options: 1. create a real AWS account and configure real AWS services. 2. use fake-aws helm charts.

* gundeck depends on sqs and sns for sending native push notifications. This needs to be synchronized with the android and iOS apps in the appstore, which gets complicated (i.e. it's currently not possible for you to have another Wire app in the apple appstore that is configured with your AWS account for push notifications). If you want to use a production installation with only the webapp and the websocket connection in android (so without native push notifications), which is what we currently support, for gundeck, fake-aws helm charts will be sufficient, because that part of the code will not really be exercised (but the gundeck process needs *something* in its configuration file to start up).

* brig depends on sqs and dynamo. sqs is used during user deletions. dynamodb is used to lock prekeys. The fake-aws charts are not highly-available, however you can hope that any running pod that dies should get respawned by kubernetes within a minute or so, leading to minimal partial downtime for some operations (adding a new device to an account; or contacting a person's new device (or a new person) for the first time, which is when prekeys are uploaded/downloaded)

**Comment by jschaul** [comment]
> Complementing the original issue I can say that I found some opensource tools which implements these interfaces:
> 
>     * [ActiveMQ](https://activemq.apache.org/) or [RabbitMQ with STOMP Plugin](https://www.rabbitmq.com/stomp.html) implements STOMP
> 
>     * [Scylla Alternator](https://www.scylladb.com/alternator/) can be used instead DynamoDB. Scylla can also replace Apache Cassandra, I heard it is more fast and less resource consuming.
> 
>     * [Atlassian LocalStack](https://github.com/localstack/localstack) can satisfy all of these dependencies (sqs, sns and dynamodb), it also can have persistent storage enabled.
> 
> 
> Is there any suggestions of trying that?

We are aware of the above list. 

* Localstack is buggy and has memory leaks, it's not production-ready at all.
* activeMQ or rabbitMQ might work for brig, however we will not currently provide support.
* ScyllaDB may work, we didn't yet try it. Feel free to try it out and report back.

**Comment by kvaps** [comment]
Hi @jschaul, thanks for the detailed response.



> brig depends on sqs and dynamo. sqs is used during user deletions. dynamodb is used to lock prekeys. The fake-aws charts are not highly-available, however you can hope that any running pod that dies should get respawned by kubernetes within a minute or so, leading to minimal partial downtime for some operations (adding a new device to an account; or contacting a person's new device (or a new person) for the first time, which is when prekeys are uploaded/downloaded)

OK, do I right understood that they are not requires any persistence storage to handle these operations?

---

> Were there any parts in the code, scripts or documentation that were unclear or initially confusing for you? Where can we improve documentation? (in case there's something small, feel free to also make a PR)

There were few controversial moments, eg. :
* I spent a lot of time fighting with CORS  in demo-installation, until find out that specifying my domain in `CSP_EXTRA_*` variables for webapp solving that.
* I also used cert-manager for issuing certificates, I was needed to modify the nginx-ingress-services to achieve that, anyway there it’s still not clear if I'm going use them for the restund, because they can be updated quite often and every time they requires the service restart to reload new certificates.
* Gundesk is missing redis section as well the redis playbook is missing itself, I took it from this PR https://github.com/wireapp/wire-server-deploy/pull/76
* There is still no [Installing wire-server (production)](https://docs.wire.com/how-to/install/helm-prod.html) section in Administrator's Guide, so I had to improvise.
I've created external endpoints in Kubernetes for the external databases, but Kubernetes have no somewhat livenessProbe for them, so I probably need to add additional loadbalancer to check their health and always keep the connection. I'm considering trying Haproxy Ingress controller for that case.
* SMTP server is missing in example chart, I wasn't able to run fake-ses because it was rejecting any mails even with specified `sesSender` field. So I was using Cloudposse's one which is working pretty well.

  <details>
  <summary>Here is my deployment file for SMTP</summary>
  <pre>
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: postfix
    namespace: default
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: postfix
    template:
      metadata:
        annotations:
        labels:
          app: postfix
      spec:
        containers:
        - image: cloudposse/postfix:0.3.1
          args: [ '--trust-rfc1918', '--mail-name', 'example.org' ]
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 25
            timeoutSeconds: 1
          name: postfix
          ports:
          - containerPort: 25
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 25
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: postfix
  spec:
    ports:
    - name: postfix
      port: 25
      protocol: TCP
      targetPort: 25
    selector:
      app: postfix
    type: ClusterIP
  </pre>
  </details>

Overall I wanted to say that the Deployment Guide is described pretty well, ansible roles and helm charts are well written and they are working really fine. 

I have no any other ideas how to improve this.
Guys, really thank you for this big work, usually it could be much worse ;)

**Comment by jschaul** [comment]
> 
> OK, do I right understood that they are not requires any persistence storage to handle these operations?

The dynamoDB part only uses "temporary" storage (create a lock, update prekey table, free the lock). SQS is used in places where we want to ensure that a user deletion is completely processed even if the process (brig) crashes half-way, as it's then retried (and since delete is implemented idempotently, it can be retried). So some form of guaranteeing this is nice. An in-memory SQS has the problem of not giving this guarantee when it crashes, so it's comparable to not using SQS at all (trading robustness against crashing of `brig` to the robusness against crashing of `SQS`), except that it allows e.g. deleting a lot of users at the same time (e.g. during a team deletion) but processing the deletions slowly.

> 
> > Were there any parts in the code, scripts or documentation that were unclear or initially confusing for you? Where can we improve documentation? (in case there's something small, feel free to also make a PR)
> 
> There were few controversial moments, eg. :
> 
>     * I spent a lot of time fighting with CORS  in demo-installation, until find out that specifying my domain in `CSP_EXTRA_*` variables for webapp solving that.

I added a section to the docs, [here](https://github.com/wireapp/wire-docs/pull/24/files). Does that cover it?

> 
>     * I also used cert-manager for issuing certificates, I was needed to modify the nginx-ingress-services to achieve that, anyway there it’s still not clear if I'm going use them for the restund, because they can be updated quite often and every time they requires the service restart to reload new certificates.

Would you be willing to make a PR to this repository with the changes you made there? We wanted to use cert-manager as well (as an option) but didn't get round to implementing that yet.

> 
>     * Gundesk is missing redis section as well the redis playbook is missing itself, I took it from this PR #76

Unfortunately that playbook/role for redis is not fully ready, i.e. master failover doesn't correctly work in some cases. An alternative is to use `redis-ephemeral` together with `https://github.com/wireapp/wire-server-deploy/tree/develop/charts/reaper`. This will lead to self-healing properties for websocket connections if the redis chart crashes.

> 
>     * There is still no [Installing wire-server (production)](https://docs.wire.com/how-to/install/helm-prod.html) section in Administrator's Guide, so I had to improvise.

yes... we plan to write this documentation, but it's not scheduled for the next month or two.

>       I've created external endpoints in Kubernetes for the external databases, but Kubernetes have no somewhat livenessProbe for them, so I probably need to add additional loadbalancer to check their health and always keep the connection. I'm considering trying Haproxy Ingress controller for that case.

> 
>     * SMTP server is missing in example chart, I wasn't able to run fake-ses because it was rejecting any mails even with specified `sesSender` field. So I was using Cloudposse's one which is working pretty well.

Have you tried https://github.com/wireapp/wire-server-deploy/tree/develop/charts/demo-smtp ?

>       
>       Here is my deployment file for SMTP
>       apiVersion: extensions/v1beta1
>       kind: Deployment
>       metadata:
>         name: postfix
>         namespace: default
>       spec:
>         replicas: 3
>         selector:
>           matchLabels:
>             app: postfix
>         template:
>           metadata:
>             annotations:
>             labels:
>               app: postfix
>           spec:
>             containers:
>             - image: cloudposse/postfix:0.3.1
>               args: [ '--trust-rfc1918', '--mail-name', 'example.org' ]
>               imagePullPolicy: IfNotPresent
>               livenessProbe:
>                 failureThreshold: 3
>                 initialDelaySeconds: 10
>                 periodSeconds: 10
>                 successThreshold: 1
>                 tcpSocket:
>                   port: 25
>                 timeoutSeconds: 1
>               name: postfix
>               ports:
>               - containerPort: 25
>                 protocol: TCP
>               readinessProbe:
>                 failureThreshold: 3
>                 initialDelaySeconds: 10
>                 periodSeconds: 10
>                 successThreshold: 1
>                 tcpSocket:
>                   port: 25
>                 timeoutSeconds: 1
>               resources:
>                 limits:
>                   cpu: 100m
>                   memory: 128Mi
>                 requests:
>                   cpu: 100m
>                   memory: 128Mi
>       ---
>       apiVersion: v1
>       kind: Service
>       metadata:
>         name: postfix
>       spec:
>         ports:
>         - name: postfix
>           port: 25
>           protocol: TCP
>           targetPort: 25
>         selector:
>           app: postfix
>         type: ClusterIP
> 
> 

Thanks for this alternative smtp deployment.

> Overall I wanted to say that the Deployment Guide is described pretty well, ansible roles and helm charts are well written and they are working really fine.
> 
> I have no any other ideas how to improve this.
> Guys, really thank you for this big work, usually it could be much worse ;)

Thanks for your feedback!

**Comment by lucendio** [comment]
@kvaps In case your issue has been resolved, we'd like to ask you closing it. Otherwise, please follow up on this in order to continue the conversation. Thank you.
