### ISSUE TITLE
brig pod errors: tls_process_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by ramesh8830** [wireapp/wire-server-deploy#247]
Hi,

I am getting below errors on the brig for aws and login with phone number.

`{"error":"GeneralError (TransportError (HttpExceptionRequest Request `
`	{\n  host                 = \"sqs.us-east-1.amazonaws.com\"\n  `
`		 port                 = 443\n  `
`		 secure               = True\n  `
`		 requestHeaders       = [(\"Host\",\"sqs.us-east-1.amazonaws.com\"),(\"X-Amz-Date\",\"20200430T013331Z\"),(\"X-Amz-Content-SHA256\",\"1bcb22493cf3e61a8a93aaf06da833295b32d77fb7ccb06cfa3bbd8cc04968e3\"),(\"Content-Type\",\"application/x-www-form-urlencoded; charset=utf-8\"),(\"Authorization\",\"<REDACTED>\")]\n  path                 = \"/\"\n`  
`		 queryString          = \"\"\n  `
`		 method               = \"POST\"\n  `
`		 proxy                = Nothing\n  `
`		 rawBody              = False\n  `
`		 redirectCount        = 0\n  `
`		 responseTimeout      = ResponseTimeoutMicro 70000000\n  `
`		 requestVersion       = HTTP/1.1\n}\n (InternalException ProtocolError \"error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed\")))","logger":"aws.brig","msgs":["E","Failed to read from SQS"]}`

`{\n  `
`	host                 = \"lookups.twilio.com\"\n  `
`	port                 = 443\n  `
`	secure               = True\n  `
`	requestHeaders       = [(\"Authorization\",\"<REDACTED>\")]\n  `
`	path                 = \"/v1/PhoneNumbers/+1xxxxxxxxxx\"\n  `
`	queryString          = \"\"\n  method               = \"GET\"\n  proxy                = Nothing\n  rawBody              = False\n  redirectCount        = 10\n  responseTimeout      = ResponseTimeoutDefault\n  requestVersion       = HTTP/1.1\n}\n (InternalException ProtocolError \"error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed\")"]}`

Please help me resolve these errors.

**Comment by lucendio** [comment]
Hi @ramesh8830 

Can you tell us more about your setup? You mentioned AWS? Do you use SQS on AWS or do you use the `fake-aws` charts? In your other issue (https://github.com/wireapp/wire-server-deploy/issues/248) you mentioned that you used minio, but if ypu are on AWS you might preper to use S3 instead of minio.

Didi you start to debug SQS, since the error states `Failed to read from SQS`. Furthermore, did you adjust the necessary [values for the wire-server chart](https://github.com/wireapp/wire-server-deploy/tree/develop/values/wire-server)? Would you mind sharing these here?

**Comment by ramesh8830** [comment]
Hi @lucendio 

Its production server setup. I am using real aws services for SQS, SNS and Dynamodb and I am using fake-aws-s3 and minio services.  

Can able to text each other on the chat but seeing those errors on the brig pod for SQS.
I managed to partially fix the minio. Now I can able to upload images but having issues with download end point. Can't see the pictures after uploading on the chat windows on both parties.

I have attached the values.yaml files. 
[values.zip](https://github.com/wireapp/wire-server-deploy/files/4578109/values.zip)

Thank you

**Comment by lucendio** [comment]
> I managed to partially fix the minio. Now I can able to upload images but having issues with download end point.

In that case, I would consider this one closed, since further discussion continuous in https://github.com/wireapp/wire-server-deploy/issues/248. One last note on this, though. One of the last webapp versions had some issues with loading assets. My colleagues over at https://github.com/wireapp/wire-server-deploy/issues/248 already hinted towards CSP, but you might want to try the latest version, by overriding the webapp image version with sth newer available from in the [repository](https://quay.io/repository/wire/webapp?tag=latest&tab=tags)
