### ISSUE TITLE
Error in $.settings.featureFlags.teamSearchVisibility: FeatureSearchVisibility: null

### ISSUE THREAD

**Issue by rahulit1991** [wireapp/wire-server-deploy#270]
Hello,

I am deploying demo server on EC2 instance. Before 3 days back everything working fine with new deployment as well. when i deploy new demo on another EC2 instance, gallery pod crashed every time. Same things happen on Google cloud as well.

**kubectl logs -f galley-7cbc886974-lxrn9**

**ERROR:** 
`service: user error (AesonException "Error in $.settings.featureFlags.teamSearchVisibility: FeatureSearchVisibility: null")`

**Comment by rahulit1991** [comment]
can any please help why my gallery pod in not running. Its **CrashLoopBackOff** everytime with above error.

**Comment by lucendio** [comment]
Hi @rahulit1991 

apparently this is a bug caused by a typo introduced [here](https://github.com/wireapp/wire-server-deploy/commit/8e0eeb93c794786abbabf6e3a2dd5cc996cc6ab0#diff-de08b88ed4d222a9d88fc8cf371b0261R28). As a quick workaround, add `galley.config.settings.featureFlags.teamSearchVisibility: 'disabled-by-default'` to the `values.yaml` for the `wire-server` chart.

A hotfix release will follow shortly.

Question is, why was the change able to pass our CI? /cc @akshaymankar

**Comment by rahulit1991** [comment]
@lucendio Thanks for reply. Yes i resolved this error following way. 
FYI, for above type issue, i check in **charts/galley/values.yaml**. changes updated. but still i am facing issue, Please check in screenshot which updated with Typo mistake. 
![Screenshot 2020-05-22 at 9 01 30 PM](https://user-images.githubusercontent.com/64314085/82683963-7a935400-9c6f-11ea-8877-e34b8889a683.png)

For resolve this issue i did following: add following values in **wire-server/value.yaml**.

 i added this content in my values.yaml

```
    settings: 
      featureFlags:
        sso: disabled-by-default
        legalhold: disabled-by-default
        teamSearchVisibility: disabled-by-default
```
Issue resolved now. Let me know if i am wrong. But you need to consider that error, as this comming after type mistake updated.

**Comment by akshaymankar** [comment]
> Question is, why was the change able to pass our CI? /cc @akshaymankar

It passed through CI undetected because we override this value in our CI config [here (internal)](https://github.com/zinfra/cailleach/blob/cc504aa6abb81c2eeee86f1003d9fdeb75bd30ba/helm_vars/integration/eu-central-1/wire-server/values.yaml#L135) and we managed to spell it right there :smile: 

However, we should add testing the example config and the steps in [docs](https://docs.wire.com/how-to/install/helm.html) to CI.
