### ISSUE TITLE
make download error

### ISSUE THREAD

**Issue by daxLMM** [wireapp/wire-server-deploy#395]
ASK [fix for kubectl role when on debian] *************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'ansible_os_family == 'Debian'' failed. The error was: error while evaluating conditional (ansible_os_family == 'Debian'): 'ansible_os_family' is undefined\n\nThe error appears to have been in '/home/l/文档/wire-server-deploy/ansible/download_cli_binaries.yml': line 29, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: fix for kubectl role when on debian\n    ^ here\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1

**Comment by lucendio** [comment]
Hi @daxLMM,

I'm sorry, but it's very hard to help you out here, since you didn't use the Issue template and thus the issue description is missing important question. Do you mind redoing it? Feel free to reopen the issue.

Only from the error message telling, this is a sole Ansible issue on your system, since `ansible_os_family` is not bt has to be defined. Please verify that you have the right Python and Ansible version installed.
